#### imports

In [1]:
import pandas as pd

# Visual Crossing Weather united states of America 2021-01-01 to 2023-03-01

In [2]:
name_of_file = 'Dallas_Texas_2019-01-01_to_2023-07-22'

In [3]:
df = pd.read_csv(f"../data/{name_of_file}.csv") # reading the csv in pandas

In [3]:
df.head() # checking the first 5 rows

,name,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,solarenergy,uvindex,severerisk,sunrise,sunset,moonphase,conditions,description,icon,stations
0,"Dallas, Texas",2019-01-01,43.1,36.5,39.2,38.3,28.6,31.8,32.0,75.3,...,4.8,3,NaN,2019-01-01T07:29:43,2019-01-01T17:31:53,0.85,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"KLNC,D7484,KDAL,72259903971,KRBD,AN483,7225801..."
1,"Dallas, Texas",2019-01-02,36.8,32.8,34.7,31.8,24.6,27.5,31.5,88.6,...,0.7,0,NaN,2019-01-02T07:29:55,2019-01-02T17:32:38,0.88,"Snow, Rain, Overcast",Cloudy skies throughout the day with a chance ...,rain,"KLNC,KDAL,72259903971,KRBD,AN483,72258013960,7..."
2,"Dallas, Texas",2019-01-03,40.2,35.4,37.7,37.2,27.6,31.3,35.6,92.2,...,2.7,2,NaN,2019-01-03T07:30:05,2019-01-03T17:33:24,0.92,"Snow, Rain, Overcast",Cloudy skies throughout the day with a chance ...,rain,"KLNC,KDAL,72259903971,KRBD,AN483,72258013960,7..."
3,"Dallas, Texas",2019-01-04,59.3,37.2,45.4,59.3,29.1,41.9,33.7,66.8,...,12.6,6,NaN,2019-01-04T07:30:13,2019-01-04T17:34:11,0.95,Partially cloudy,Clearing in the afternoon.,partly-cloudy-day,"KLNC,D7484,KDAL,72259903971,KRBD,AN483,7225801..."
4,"Dallas, Texas",2019-01-05,70.9,37.3,53.1,70.9,37.3,52.9,37.1,57.9,...,13.0,6,NaN,2019-01-05T07:30:20,2019-01-05T17:34:59,0.00,Clear,Clear conditions throughout the day.,clear-day,"KLNC,D7484,KDAL,72259903971,KRBD,AN483,7225801..."

In [4]:
df.shape

(1664, 33)

In [6]:
df['idx'] = df.index # adding an index column as required by AutoML
df.head()

,name,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,uvindex,severerisk,sunrise,sunset,moonphase,conditions,description,icon,stations,idx
0,"Dallas, Texas",2019-01-01,43.1,36.5,39.2,38.3,28.6,31.8,32.0,75.3,...,3,NaN,2019-01-01T07:29:43,2019-01-01T17:31:53,0.85,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"KLNC,D7484,KDAL,72259903971,KRBD,AN483,7225801...",0
1,"Dallas, Texas",2019-01-02,36.8,32.8,34.7,31.8,24.6,27.5,31.5,88.6,...,0,NaN,2019-01-02T07:29:55,2019-01-02T17:32:38,0.88,"Snow, Rain, Overcast",Cloudy skies throughout the day with a chance ...,rain,"KLNC,KDAL,72259903971,KRBD,AN483,72258013960,7...",1
2,"Dallas, Texas",2019-01-03,40.2,35.4,37.7,37.2,27.6,31.3,35.6,92.2,...,2,NaN,2019-01-03T07:30:05,2019-01-03T17:33:24,0.92,"Snow, Rain, Overcast",Cloudy skies throughout the day with a chance ...,rain,"KLNC,KDAL,72259903971,KRBD,AN483,72258013960,7...",2
3,"Dallas, Texas",2019-01-04,59.3,37.2,45.4,59.3,29.1,41.9,33.7,66.8,...,6,NaN,2019-01-04T07:30:13,2019-01-04T17:34:11,0.95,Partially cloudy,Clearing in the afternoon.,partly-cloudy-day,"KLNC,D7484,KDAL,72259903971,KRBD,AN483,7225801...",3
4,"Dallas, Texas",2019-01-05,70.9,37.3,53.1,70.9,37.3,52.9,37.1,57.9,...,6,NaN,2019-01-05T07:30:20,2019-01-05T17:34:59,0.00,Clear,Clear conditions throughout the day.,clear-day,"KLNC,D7484,KDAL,72259903971,KRBD,AN483,7225801...",4

In [8]:
# writing back to new csv with the idx column (remember to not add index again)
df.to_csv(f"../data/{name_of_file}_w_index.csv", sep=',', header=True,index=False)

In [9]:
df.reindex(sorted(df.columns), axis=1).head(3)

,cloudcover,conditions,datetime,description,dew,feelslike,feelslikemax,feelslikemin,humidity,icon,...,sunrise,sunset,temp,tempmax,tempmin,uvindex,visibility,winddir,windgust,windspeed
0,81.9,Partially cloudy,2019-01-01,Partly cloudy throughout the day.,32.0,31.8,38.3,28.6,75.3,partly-cloudy-day,...,2019-01-01T07:29:43,2019-01-01T17:31:53,39.2,43.1,36.5,3,9.7,350.2,24.2,15.2
1,95.0,"Snow, Rain, Overcast",2019-01-02,Cloudy skies throughout the day with a chance ...,31.5,27.5,31.8,24.6,88.6,rain,...,2019-01-02T07:29:55,2019-01-02T17:32:38,34.7,36.8,32.8,0,6.7,347.0,19.7,14.9
2,93.2,"Snow, Rain, Overcast",2019-01-03,Cloudy skies throughout the day with a chance ...,35.6,31.3,37.2,27.6,92.2,rain,...,2019-01-03T07:30:05,2019-01-03T17:33:24,37.7,40.2,35.4,2,6.3,308.7,19.7,13.4

In [10]:
pd.set_option('display.max_columns', None)

In [11]:
df.severerisk.nunique()

8

In [12]:
df.reindex(sorted(df.columns), axis=1).select_dtypes(include="object").columns

Index(['conditions', 'datetime', 'description', 'icon', 'name', 'preciptype',
       'stations', 'sunrise', 'sunset'],
      dtype='object')

In [13]:
df.columns

Index(['name', 'datetime', 'tempmax', 'tempmin', 'temp', 'feelslikemax',
       'feelslikemin', 'feelslike', 'dew', 'humidity', 'precip', 'precipprob',
       'precipcover', 'preciptype', 'snow', 'snowdepth', 'windgust',
       'windspeed', 'winddir', 'sealevelpressure', 'cloudcover', 'visibility',
       'solarradiation', 'solarenergy', 'uvindex', 'severerisk', 'sunrise',
       'sunset', 'moonphase', 'conditions', 'description', 'icon', 'stations',
       'idx'],
      dtype='object')

In [14]:
num_rows = df.shape[0]
num_rows

1664

In [15]:
train_size = 0.8
val_size = 0.1
test_size = 0.1
train_index = round(train_size*num_rows)
val_index = round((train_size+val_size)*num_rows)
print(train_index,val_index)

1331 1498

In [16]:
df_test = df.iloc[val_index:]
df_test.head()

,name,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,precip,precipprob,precipcover,preciptype,snow,snowdepth,windgust,windspeed,winddir,sealevelpressure,cloudcover,visibility,solarradiation,solarenergy,uvindex,severerisk,sunrise,sunset,moonphase,conditions,description,icon,stations,idx
1498,"Dallas, Texas",2023-02-07,63.4,47.6,57.1,63.4,42.5,56.1,53.7,88.7,0.300,100.0,33.33,rain,0.0,0.0,28.0,14.0,103.5,1015.6,99.1,8.3,31.9,2.6,2,10.0,2023-02-07T07:17:43,2023-02-07T18:05:23,0.57,"Rain, Overcast",Cloudy skies throughout the day with rain.,rain,"F8578,KDAL,72259903971,KRBD,72258013960",1498
1499,"Dallas, Texas",2023-02-08,48.5,39.8,45.5,44.6,37.1,40.6,43.1,91.5,0.653,100.0,62.50,rain,0.0,0.0,33.3,16.9,293.3,1015.7,84.2,8.0,21.6,1.8,1,10.0,2023-02-08T07:16:53,2023-02-08T18:06:18,0.60,"Rain, Partially cloudy",Partly cloudy throughout the day with a chance...,rain,"F8578,KDAL,72259903971,KRBD,72258013960",1499
1500,"Dallas, Texas",2023-02-09,64.1,34.4,48.2,64.1,31.8,47.5,39.5,74.5,0.039,100.0,4.17,"rain,snow",0.0,0.0,23.0,12.3,19.1,1018.3,13.7,9.8,241.4,20.8,9,10.0,2023-02-09T07:16:02,2023-02-09T18:07:13,0.64,"Snow, Rain",Clear conditions throughout the day with morni...,rain,"F8578,KDAL,72259903971,KRBD,72258013960",1500
1501,"Dallas, Texas",2023-02-10,50.0,37.5,43.2,45.3,31.6,36.3,32.8,66.8,0.000,0.0,0.00,rain,0.0,0.0,34.9,21.5,337.7,1027.7,99.1,9.9,105.8,9.3,4,10.0,2023-02-10T07:15:10,2023-02-10T18:08:08,0.67,Overcast,Cloudy skies throughout the day.,cloudy,"F8578,KDAL,72259903971,KRBD,72258013960",1501
1502,"Dallas, Texas",2023-02-11,54.7,35.6,43.7,54.7,27.3,40.1,33.3,68.0,0.000,0.0,0.00,NaN,0.0,0.0,21.9,13.6,334.6,1026.6,45.9,9.9,220.7,19.1,9,10.0,2023-02-11T07:14:16,2023-02-11T18:09:03,0.71,Partially cloudy,Clearing in the afternoon.,partly-cloudy-day,"F8578,KDAL,72259903971,KRBD,72258013960",1502

In [17]:
df_test[['datetime','idx']].to_csv(f"../data/test_{name_of_file}_w_index.csv", sep=',', header=True,index=False)

In [18]:
df_test[['datetime','idx']]

        datetime   idx
1498  2023-02-07  1498
1499  2023-02-08  1499
1500  2023-02-09  1500
1501  2023-02-10  1501
1502  2023-02-11  1502
...          ...   ...
1659  2023-07-18  1659
1660  2023-07-19  1660
1661  2023-07-20  1661
1662  2023-07-21  1662
1663  2023-07-22  1663

[166 rows x 2 columns]

In [20]:
index = 'idx'
timeseries='datetime'
target='tempmax', 'tempmin'
columns_to_ignore = ['name','temp', 'feelslikemax','feelslikemin', 'feelslike', 
                     'precip', 'precipprob', 'preciptype', 'snow', 'snowdepth', 
                     'severerisk','moonphase', 'conditions', 'description', 'icon', 'stations',
                    ]
columns_to_train = [
    'dew', 'humidity', 'precipcover','windgust','windspeed', 'winddir', 
    'sealevelpressure', 'cloudcover', 'visibility', 'solarradiation', 'solarenergy', 
    'uvindex', 'sunrise','sunset', 
    ]

In [8]:
df_test = df.iloc[-168:,:]
df_test

,name,datetime,tempmax,tempmin,temp,feelslikemax,feelslikemin,feelslike,dew,humidity,...,uvindex,severerisk,sunrise,sunset,moonphase,conditions,description,icon,stations,idx
1496,"Dallas, Texas",2023-02-05,70.4,41.3,56.0,70.4,39.5,55.0,45.5,70.1,...,9,10.0,2023-02-05T07:19:19,2023-02-05T18:03:31,0.50,Clear,Clear conditions throughout the day.,clear-day,"F8578,KDAL,72259903971,KRBD,72258013960",1496
1497,"Dallas, Texas",2023-02-06,71.6,52.7,62.5,71.6,52.7,62.5,54.2,75.3,...,7,10.0,2023-02-06T07:18:32,2023-02-06T18:04:27,0.53,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,"F8578,KDAL,72259903971,KRBD,72258013960",1497
1498,"Dallas, Texas",2023-02-07,63.4,47.6,57.1,63.4,42.5,56.1,53.7,88.7,...,2,10.0,2023-02-07T07:17:43,2023-02-07T18:05:23,0.57,"Rain, Overcast",Cloudy skies throughout the day with rain.,rain,"F8578,KDAL,72259903971,KRBD,72258013960",1498
1499,"Dallas, Texas",2023-02-08,48.5,39.8,45.5,44.6,37.1,40.6,43.1,91.5,...,1,10.0,2023-02-08T07:16:53,2023-02-08T18:06:18,0.60,"Rain, Partially cloudy",Partly cloudy throughout the day with a chance...,rain,"F8578,KDAL,72259903971,KRBD,72258013960",1499
1500,"Dallas, Texas",2023-02-09,64.1,34.4,48.2,64.1,31.8,47.5,39.5,74.5,...,9,10.0,2023-02-09T07:16:02,2023-02-09T18:07:13,0.64,"Snow, Rain",Clear conditions throughout the day with morni...,rain,"F8578,KDAL,72259903971,KRBD,72258013960",1500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1659,"Dallas, Texas",2023-07-18,109.3,87.0,98.9,109.0,90.5,99.4,59.9,29.8,...,9,15.0,2023-07-18T06:31:48,2023-07-18T20:34:52,0.03,Clear,Clear conditions throughout the day.,clear-day,NaN,1659
1660,"Dallas, Texas",2023-07-19,108.6,86.1,98.1,110.6,90.0,99.8,62.3,32.9,...,9,30.0,2023-07-19T06:32:25,2023-07-19T20:34:22,0.06,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,NaN,1660
1661,"Dallas, Texas",2023-07-20,103.4,83.4,93.4,105.3,86.8,95.9,64.9,41.1,...,9,10.0,2023-07-20T06:33:03,2023-07-20T20:33:51,0.10,Partially cloudy,Clearing in the afternoon.,partly-cloudy-day,NaN,1661
1662,"Dallas, Texas",2023-07-21,103.2,83.0,92.8,106.1,85.6,95.6,65.4,41.9,...,9,10.0,2023-07-21T06:33:41,2023-07-21T20:33:19,0.13,Clear,Clear conditions throughout the day.,clear-day,NaN,1662
1663,"Dallas, Texas",2023-07-22,104.6,84.3,95.3,105.6,87.3,97.2,63.5,37.1,...,9,10.0,2023-07-22T06:34:19,2023-07-22T20:32:45,0.16,Partially cloudy,Partly cloudy throughout the day.,partly-cloudy-day,NaN,1663

In [9]:
df_test.to_csv(f"../data/test_{name_of_file}_w_index.csv", sep=',', header=True,index=False)